# Generated by Django 2.2.2 on 2020-03-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tedsearchterm',
            name='notifications',
        ),
        migrations.AddField(
            model_name='tedsearchterm',
            name='send_notifications',
            field=models.BooleanField(default=True, help_text='Send email notifications when search term matches a Contract Notice', verbose_name='Send Notifications'),
        ),
        migrations.AlterField(
            model_name='tedsearchterm',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Use search term to find matching Contract Notices', verbose_name='Is Active'),
        ),
    ]
