# Generated by Django 2.2.2 on 2019-11-27 14:07

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import tenders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Added to Database Timestamp')),
                ('ojs_ref', models.CharField(max_length=17, unique=True, verbose_name='OJS Reference')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=700)),
                ('short_descr', models.TextField(verbose_name='Short Description')),
                ('contracting_body_name', models.CharField(max_length=400, verbose_name='Contracting Body Name')),
                ('closing_date', models.DateTimeField(verbose_name='Closing Date')),
                ('dispatch_date', models.DateField(verbose_name='Dispatch Date')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('procurement_ref', models.CharField(blank=True, max_length=140, null=True, verbose_name='Procurement Reference')),
                ('procurement_docs_url', models.URLField(verbose_name='Procurement Documents Location')),
                ('full_docs_available', models.BooleanField(default=True)),
                ('procurement_docs_file', models.FileField(blank=True, null=True, upload_to=tenders.models.contract_notice_file_path, verbose_name='Procurement Document File')),
            ],
            options={
                'verbose_name': 'Contract Notice',
                'ordering': ['ojs_ref'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=2, unique=True, verbose_name='ISO Code')),
                ('country_name', models.CharField(max_length=140, verbose_name='Country Name')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['iso_code'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='ISO Code')),
                ('currency_name', models.CharField(max_length=140, verbose_name='Currency Name')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['iso_code'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Added to Database Timestamp')),
                ('lot_no', models.PositiveIntegerField(verbose_name='Lot No.')),
                ('awarded_contract', models.BooleanField(default=False, verbose_name='Awarded Contract')),
                ('title', models.CharField(max_length=400)),
                ('short_descr', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('info_add', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('conclusion_date', models.DateField(blank=True, null=True, verbose_name='Conclusion Date')),
                ('contractor_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Contractor Name')),
                ('awarded_to_group', models.BooleanField(default=False, verbose_name='Awarded To Group')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('value_estimated', models.BooleanField(default=False)),
                ('number_of_units', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Units')),
                ('value_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Value per Unit')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('contract_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.ContractNotice')),
                ('contractor_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.Country', verbose_name='Contractor Country')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.Currency')),
            ],
            options={
                'ordering': ['contract_notice', 'lot_no'],
            },
        ),
        migrations.AddField(
            model_name='contractnotice',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.Country'),
        ),
        migrations.CreateModel(
            name='ContractAwardNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Added to Database Timestamp')),
                ('ojs_ref', models.CharField(max_length=17, unique=True, verbose_name='OJS Reference')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=700)),
                ('short_descr', models.TextField(verbose_name='Short Description')),
                ('contracting_body_name', models.CharField(max_length=400, verbose_name='Contracting Body Name')),
                ('dispatch_date', models.DateField(verbose_name='Dispatch Date')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('length_of_tender', models.DurationField(blank=True, null=True, verbose_name='Length of Tender')),
                ('value_of_procurement', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Value of Procurement')),
                ('contract_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.ContractNotice')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.Country')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.Currency')),
            ],
            options={
                'verbose_name': 'Contract Award Notice',
                'ordering': ['ojs_ref'],
            },
        ),
    ]
