# Generated by Django 2.2.2 on 2019-12-09 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='contract_notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.ContractNotice', verbose_name='Contract Notice'),
        ),
    ]
