# Generated by Django 2.2.2 on 2019-08-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added Timestamp')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('filename', models.CharField(max_length=140, unique=True, verbose_name='Filename')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Idle'), (1, 'Downloading bulk data file from S3'), (2, 'Error in downloading bulk data file'), (3, 'Processing bulk data file'), (4, 'Error in processing bulk data file'), (5, 'Download and processing of bulk data file complete')], default=0, verbose_name='Status')),
                ('status_msg', models.CharField(blank=True, max_length=400, null=True, verbose_name='Status Message')),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
    ]
