# Generated by Django 2.2.2 on 2019-08-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadtaskstatus',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'IDLE'), (1, 'DOWNLOADING'), (2, 'DOWNLOADING ERROR'), (3, 'PROCESSING'), (4, 'PROCESSING ERROR'), (5, 'COMPLETE')], default=0, verbose_name='Status'),
        ),
    ]
