# Generated by Django 2.2.2 on 2019-09-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190822_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPackageDownloadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added Timestamp')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('file_name', models.CharField(max_length=140, unique=True, verbose_name='File Name')),
                ('file_date', models.DateTimeField(verbose_name='File Date')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Idle'), (1, 'Downloading'), (2, 'Processing'), (3, 'Error'), (4, 'Complete')], default=0, verbose_name='Status')),
                ('status_msg', models.CharField(blank=True, max_length=400, null=True, verbose_name='Status Message')),
            ],
            options={
                'verbose_name_plural': 'Daily Package Download Statuses',
                'ordering': ['file_date'],
                'verbose_name': 'Daily Package Download Status',
            },
        ),
        migrations.DeleteModel(
            name='BulkUploadTaskStatus',
        ),
    ]
