# Generated by Django 2.2.2 on 2020-03-29 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20190917_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailypackagedownloadstatus',
            options={'ordering': ['-file_date'], 'verbose_name': 'Daily Package Download Status', 'verbose_name_plural': 'Daily Package Download Statuses'},
        ),
        migrations.AlterField(
            model_name='dailypackagedownloadstatus',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Idle'), (1, 'Downloading'), (2, 'Processing'), (3, 'Error'), (4, 'Timeout'), (5, 'Complete')], default=0, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='EmailNotificationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added Timestamp')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Idle'), (1, 'Processing'), (2, 'Error'), (3, 'Complete')], default=0, verbose_name='Status')),
                ('status_msg', models.CharField(blank=True, max_length=400, null=True, verbose_name='Status Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Notification Status',
                'ordering': ['-publication_date'],
                'verbose_name_plural': 'Email Notification Statuses',
            },
        ),
    ]
