# Generated by Django 2.2.2 on 2020-01-12 20:38

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BNFChemicalSubstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
                'verbose_name': 'BNF Chemical Substance',
            },
        ),
        migrations.CreateModel(
            name='BNFProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, verbose_name='Code')),
                ('name', models.CharField(max_length=140, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_generic', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
                'verbose_name': 'BNF Product',
            },
        ),
        migrations.CreateModel(
            name='BNFPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=140, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('chem_substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.BNFChemicalSubstance', verbose_name='BNF Chemical Substance')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.BNFProduct', verbose_name='BNF Product')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
